// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/12/2026, 5:41:52 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/DEV/YJ/job-board/client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/DEV/YJ/job-board/client/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/DEV/YJ/job-board/client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/DEV/YJ/job-board/client/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/DEV/YJ/job-board/client/app/plugins/**/*.{js,ts,mjs}","C:/DEV/YJ/job-board/client/app/composables/**/*.{js,ts,mjs}","C:/DEV/YJ/job-board/client/app/utils/**/*.{js,ts,mjs}","C:/DEV/YJ/job-board/client/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/DEV/YJ/job-board/client/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/DEV/YJ/job-board/client/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/DEV/YJ/job-board/client/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;